# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: xenial
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=pincers

matrix:
  include:
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-pc-windows-gnu
      os: windows
    # env: TARGET=x86_64-unknown-freebsd
    # env: TARGET=x86_64-unknown-netbsd
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - rustup self update
  - which cross 2>/dev/null || cargo install cross

script:
  - rustup target install $TARGET || true
  - cross test --target $TARGET

before_deploy:
  - set -e
  - cross build --target $TARGET --release
  - cp target/$TARGET/release/pincers $CRATE_NAME-$TRAVIS_TAG-$TARGET

deploy:
  api_key:
    secure: BocTJ0/GDqTbdKIF2RVr+4i4zQQZ/SLYIR6sWT+SwiwRT8vqKq4ke0ENtGY0YX5wJ8IAoKYHfubIg4c0UN2tj5ZjozJF/ZoefPpn4NycBqFudUdxEBIhO8LXBAjLWJmMlka96KB6i+vGtrBJH4bGz/bJviibNZ9Ubx7XQvKtWZ3gQLQHHEGiREP7eEZrC7zsjlfr9Vv8NvdcphbvsuanUMwnxRbDOEahjvxUS2sAX/CBfVFiAUt7oGJaOS3PiLoLTEt1yb9ViG7fU2mPrgDOxIx6MvQJ08Y90Jc+HFH670Sp+sh1GSHQXRas2wMlBO5/VB0LAFfyfPRp4MTvpjR8KngjlVDfSpSj2Aip0X/M+cWcpRrGxrDYg0DSh9d0yaidIVgaR2P4KNr+N/8G9OEVeiuP29CjvOTqt16l+m9nlpMKgssOP6XkM37WHVqgo9pRG71dt03/LE5msDW+umbsrQ9b2G1fLwZPllpN/7FeRG9MIKF90sBmqD0iIL9JOXpXOYSYCCtbm2Y80HmJW//VlmBlA2WbU1wCzixdmlQzHJ7tVmlXogXdjc2RElC9oiq6V8f25ddpGj4KkE/523tT5pkuCQ8RPflH8pHk2XXFvo28U7Jr12jMJD3KLUOr+pqJIONFJdMEZP8dC0/bNPPg6FBWtxOBGwAQcGc2ICxpYFk=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
