# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: xenial
language: rust
services: docker
env:
  global:
  - CRATE_NAME=pincers

matrix:
  include:
  - env: TARGET=arm-unknown-linux-gnueabi
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-pc-windows-msvc
    os: windows
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
# - env: TARGET=x86_64-unknown-freebsd
# - env: TARGET=x86_64-unknown-netbsd

before_install:
- rustup self update
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo install --version 0.1.16 cross;
  sudo apt-get install -yq upx; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install upx; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install upx; fi

script:
- rustup target install $TARGET || true
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross test --target $TARGET; fi
- if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then cargo test --target $TARGET; fi

before_deploy:
- set -e
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cross build --target $TARGET --release;
  cp target/$TARGET/release/$CRATE_NAME $CRATE_NAME-$TRAVIS_TAG-$TARGET; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cargo build --target $TARGET --release;
  cp target/$TARGET/release/$CRATE_NAME.exe $CRATE_NAME-$TRAVIS_TAG-$TARGET.exe; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo build --target $TARGET --release;
  cp target/$TARGET/release/$CRATE_NAME $CRATE_NAME-$TRAVIS_TAG-$TARGET; fi
- upx $CRATE_NAME-$TRAVIS_TAG-$TARGET*

deploy:
  provider: releases
  api_key:
    secure: SE2K7UOgygToN6HfOdYWCk3uck7k7HHJQ896HMe7vsZm2xyhjxDwelyBcTAd54Z3s+tB6EHJnqEhy8GOcx63jOzHLvQtL7ZP8DwtoBcQHGgin9QpXbRI1im9RAemcQKMP9gaQOagpK4gUx1DZ7wNNo2jL3moFgpwXa/ZjiuMCNlFeyLwdW4At11Uq8VIGQCJLchTA4SQwuykm4O5PKSwyUxOGeI48tYY45AsavFg86lOemGf5D2i28yx4GS/pcoHcjksCrcDRvsH2Invj3bv502t9vGBP06Ob1n10dBaIObdZoiUDslTeFj/cZeTaEGxSWvY8IND6TCvqOHUgm3Onel80ObcnkoDizJhRpKLplro/niq4ZIgr33EFCVcHCIihBD9GnjnS2E/Uya+rUSK5GX5o04SntWetxhBWgHkFJZxM2hpjV+2/RzsAY2/83xGfD2Y+C0ZL9i2Tm7Vj7giF2x62DXpKR9zBVPsz2orK20uRxNSX8OwBNpwovxXKw2ieDg4u8O8Wv+GEtWnRI0tEnvuDEwWRH/xTnT/0BnZF6uR5nADtCFEnZ8fwkdzXaCE/CvwKSTzH+lt5gOTETiASOdH+YsnIpW1c+2+vCU/710VzL1lcgXJjVhRfsITvz4NAVEFWXwv/QIuuQypl7YsU8didBqK1nJ9Anaz9wzb5zQ=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET*
  on:
    repo: lutostag/pincers
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable
  skip_cleanup: true

cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
